[theme]
primaryColor = "#00C853"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxMessageSize = 200
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
